#include <SOIL/SOIL.h>
#include <GL/glew.h>
#include <GL/freeglut.h>
#include <stdlib.h>
#include <stdio.h>
#include <SDL/SDL.h>
#include <SDL/SDL_mixer.h>
#include "desenhanave.h"
#include "carregatextura.h"
#include "redimensiona.h"
#include "variaveisglobais.h"
#include "eventosteclado.h"
#include "ladospriteandando.h"
#include "desenhaeatualiza.h"
#include "inicializa.h"
#include "atiracaninha.h"